### ISSUE TITLE
Speedtest Tracker - Application Initialization Fails Due to Missing APP_KEY

### ISSUE THREAD

**Issue by OriginalSimon** [runtipi/runtipi-appstore#4243]
### Store Application

Speedtest Tracker

### App version

0.20.7

### Description

I am experiencing an issue with initializing the Speedtest Tracker application. The application fails to start because it cannot find the APP_KEY.

### Steps to reproduce

1. Install the Speedtest Tracker application by following the standard installation procedure.
2. Observe the application during initialization.

### App logs

```bash
Версия:
Internet performance tracking application.
Выполняется
Максимум строк:

speedtest-tracker     | [migrations] started
speedtest-tracker     | [migrations] 01-nginx-site-confs-default: executing...
speedtest-tracker     | [migrations] 01-nginx-site-confs-default: succeeded
speedtest-tracker     | [migrations] done
speedtest-tracker     | ───────────────────────────────────────
speedtest-tracker     |
speedtest-tracker     |       ██╗     ███████╗██╗ ██████╗
speedtest-tracker     |       ██║     ██╔════╝██║██╔═══██╗
speedtest-tracker     |       ██║     ███████╗██║██║   ██║
speedtest-tracker     |       ██║     ╚════██║██║██║   ██║
speedtest-tracker     |       ███████╗███████║██║╚██████╔╝
speedtest-tracker     |       ╚══════╝╚══════╝╚═╝ ╚═════╝
speedtest-tracker     |
speedtest-tracker     |    Brought to you by linuxserver.io
speedtest-tracker     | ───────────────────────────────────────
speedtest-tracker     |
speedtest-tracker-db  | The files belonging to this database system will be owned by user "postgres".
speedtest-tracker-db  | This user must also own the server process.
speedtest-tracker-db  |
speedtest-tracker-db  | The database cluster will be initialized with locale "en_US.utf8".
speedtest-tracker-db  | The default database encoding has accordingly been set to "UTF8".
speedtest-tracker-db  | The default text search configuration will be set to "english".
speedtest-tracker-db  |
speedtest-tracker-db  | Data page checksums are disabled.
speedtest-tracker-db  |
speedtest-tracker-db  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
speedtest-tracker-db  | creating subdirectories ... ok
speedtest-tracker-db  | selecting dynamic shared memory implementation ... posix
speedtest-tracker-db  | selecting default max_connections ... 100
speedtest-tracker-db  | selecting default shared_buffers ... 128MB
speedtest-tracker-db  | selecting default time zone ... Etc/UTC
speedtest-tracker-db  | creating configuration files ... ok
speedtest-tracker-db  | running bootstrap script ... ok
speedtest-tracker-db  | performing post-bootstrap initialization ... ok
speedtest-tracker-db  | syncing data to disk ... ok
speedtest-tracker-db  |
speedtest-tracker-db  |
speedtest-tracker-db  | Success. You can now start the database server using:
speedtest-tracker-db  |
speedtest-tracker-db  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
speedtest-tracker-db  |
speedtest-tracker-db  | initdb: warning: enabling "trust" authentication for local connections
speedtest-tracker-db  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
speedtest-tracker-db  | waiting for server to start....2024-07-26 08:04:16.033 UTC [49] LOG:  starting PostgreSQL 15.7 (Debian 15.7-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
speedtest-tracker-db  | 2024-07-26 08:04:16.034 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
speedtest-tracker-db  | 2024-07-26 08:04:16.040 UTC [52] LOG:  database system was shut down at 2024-07-26 08:04:15 UTC
speedtest-tracker-db  | 2024-07-26 08:04:16.045 UTC [49] LOG:  database system is ready to accept connections
speedtest-tracker-db  |  done
speedtest-tracker-db  | server started
speedtest-tracker-db  | CREATE DATABASE
speedtest-tracker-db  |
speedtest-tracker-db  |
speedtest-tracker-db  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
speedtest-tracker-db  |
speedtest-tracker-db  | 2024-07-26 08:04:16.230 UTC [49] LOG:  received fast shutdown request
speedtest-tracker-db  | waiting for server to shut down....2024-07-26 08:04:16.231 UTC [49] LOG:  aborting any active transactions
speedtest-tracker-db  | 2024-07-26 08:04:16.233 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
speedtest-tracker-db  | 2024-07-26 08:04:16.233 UTC [50] LOG:  shutting down
speedtest-tracker-db  | 2024-07-26 08:04:16.234 UTC [50] LOG:  checkpoint starting: shutdown immediate
speedtest-tracker-db  | 2024-07-26 08:04:16.275 UTC [50] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.015 s, sync=0.022 s, total=0.042 s; sync files=301, longest=0.001 s, average=0.001 s; distance=4222 kB, estimate=4222 kB
speedtest-tracker-db  | 2024-07-26 08:04:16.282 UTC [49] LOG:  database system is shut down
speedtest-tracker-db  |  done
speedtest-tracker-db  | server stopped
speedtest-tracker-db  |
speedtest-tracker-db  | PostgreSQL init process complete; ready for start up.
speedtest-tracker-db  |
speedtest-tracker-db  | 2024-07-26 08:04:16.384 UTC [1] LOG:  starting PostgreSQL 15.7 (Debian 15.7-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
speedtest-tracker-db  | 2024-07-26 08:04:16.384 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
speedtest-tracker-db  | 2024-07-26 08:04:16.384 UTC [1] LOG:  listening on IPv6 address "::", port 5432
speedtest-tracker-db  | 2024-07-26 08:04:16.387 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
speedtest-tracker-db  | 2024-07-26 08:04:16.393 UTC [65] LOG:  database system was shut down at 2024-07-26 08:04:16 UTC
speedtest-tracker-db  | 2024-07-26 08:04:16.401 UTC [1] LOG:  database system is ready to accept connections
speedtest-tracker-db  | 2024-07-26 08:09:16.488 UTC [63] LOG:  checkpoint starting: time
speedtest-tracker-db  | 2024-07-26 08:09:20.626 UTC [63] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.128 s, sync=0.005 s, total=4.139 s; sync files=12, longest=0.002 s, average=0.001 s; distance=252 kB, estimate=252 kB
speedtest-tracker     | To support the app dev(s) visit:
speedtest-tracker     | speedtest-tracker: https://github.com/sponsors/alexjustesen
speedtest-tracker     |
speedtest-tracker     | To support LSIO projects visit:
speedtest-tracker     | https://www.linuxserver.io/donate/
speedtest-tracker     |
speedtest-tracker     | ───────────────────────────────────────
speedtest-tracker     | GID/UID
speedtest-tracker     | ───────────────────────────────────────
speedtest-tracker     |
speedtest-tracker     | User UID:    1000
speedtest-tracker     | User GID:    1000
speedtest-tracker     | ───────────────────────────────────────
speedtest-tracker     | Linuxserver.io version: v0.20.7-ls35
speedtest-tracker     | Build-date: 2024-07-19T21:42:06+00:00
speedtest-tracker     | ───────────────────────────────────────
speedtest-tracker     |
speedtest-tracker     | Setting resolver to  127.0.0.11
speedtest-tracker     | Setting worker_processes to 4
speedtest-tracker     | generating self-signed keys in /config/keys, you can replace these with your own keys if required
speedtest-tracker     | ........+........+...+++++++++++++++++++++++++++++++++++++++*........+....+........+++++++++++++++++++++++++++++++++++++++*..+.+...........+...................+........+...+...+....+........+...+....+..+....+.....+.+.....+......+............+...+..........+...+.........+..++++++
speedtest-tracker     | .....+.........+......+++++++++++++++++++++++++++++++++++++++*....+...+.....+++++++++++++++++++++++++++++++++++++++*................+...+..+.+......+.........+.................+.........+...+......+.........+.......+........................+.....+......+..........+...+..++++++
speedtest-tracker     | -----
speedtest-tracker     | Waiting for DB to be available
speedtest-tracker     | An application key is missing, halting init!
speedtest-tracker     | You can generate a key at https://speedtest-tracker.dev/.
```

### Browser

Firefox, Chromium

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by sergi0g** [comment]
I have the same issue. For a temporary workaround, set it with a user config.

**Comment by OriginalSimon** [comment]
It's been two weeks since I solved the problem. I left it open just as a report.

**Comment by cori** [comment]
oh lol i didn't even see this when i [ran into this](https://discord.com/channels/976934649643294750/1271824862679404556/1271824865296650242). I just opened #4452 with my version of manual fixes.

**Comment by JigSawFr** [comment]
> oh lol i didn't even see this when i [ran into this](https://discord.com/channels/976934649643294750/1271824862679404556/1271824865296650242). I just opened #4452 with my version of manual fixes.

Thank you so much !
